CREATE TABLE IF NOT EXISTS `user_session` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `session_id` varchar(100) NOT NULL COMMENT 'Value generated by PHPs builtin function',
  `session_date` datetime NOT NULL,
  `duration` int(10) NOT NULL,
  `keep_alive` tinyint(1) NOT NULL,
  `fk_user_id` int(10) unsigned NOT NULL,
  `closed` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_user_session_1` (`fk_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `user_videohistory` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `fk_user_id` int(10) unsigned NOT NULL,
  `fk_user_session_id` int(10) unsigned NOT NULL,
  `fk_exercise_id` int(10) unsigned NOT NULL,
  `response_attempt` tinyint(1) NOT NULL DEFAULT '0',
  `fk_response_id` int(10) unsigned DEFAULT NULL,
  `incidence_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `subtitles_are_used` tinyint(1) NOT NULL DEFAULT '0',
  `fk_subtitle_id` int(10) unsigned DEFAULT NULL,
  `fk_exercise_role_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_videohistory_1` (`fk_user_id`),
  KEY `FK_user_videohistory_2` (`fk_user_session_id`),
  KEY `FK_user_videohistory_3` (`fk_exercise_id`),
  KEY `FK_user_videohistory_4` (`fk_response_id`),
  KEY `FK_user_videohistory_5` (`fk_subtitle_id`),
  KEY `FK_user_videohistory_6` (`fk_exercise_role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `user_session`
  ADD CONSTRAINT `FK_user_session_1` FOREIGN KEY (`fk_user_id`) REFERENCES `users` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `user_videohistory`
  ADD CONSTRAINT `FK_user_videohistory_1` FOREIGN KEY (`fk_user_id`) REFERENCES `users` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_user_videohistory_2` FOREIGN KEY (`fk_user_session_id`) REFERENCES `user_session` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_user_videohistory_3` FOREIGN KEY (`fk_exercise_id`) REFERENCES `exercise` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_user_videohistory_4` FOREIGN KEY (`fk_response_id`) REFERENCES `response` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_user_videohistory_5` FOREIGN KEY (`fk_subtitle_id`) REFERENCES `subtitle` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_user_videohistory_6` FOREIGN KEY (`fk_exercise_role_id`) REFERENCES `exercise_role` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

UPDATE `preferences` SET `prefValue` =  '$Revision: 520 $'  WHERE `preferences`.`prefName` = 'dbrevision';


