DELETE FROM exercise_descriptor WHERE id>0;

INSERT INTO exercise_descriptor (id,situation,level,competence,number,alte) VALUES 
(1,1,1,13,1,0),
(2,1,1,15,1,0),
(3,1,1,15,2,0),
(4,1,1,16,1,0),
(5,1,1,17,1,1),
(6,1,1,17,2,1),
(7,1,2,1,1,1),
(8,1,2,2,1,0),
(9,1,2,2,2,0),
(10,1,2,2,3,0),
(11,1,2,2,4,0),
(12,1,2,2,5,0),
(13,1,2,2,6,0),
(14,1,2,6,1,1),
(15,1,2,6,2,1),
(16,1,2,6,3,1),
(17,1,2,6,4,1),
(18,1,2,7,1,1),
(19,1,2,7,2,0),
(20,1,2,7,3,0),
(21,1,2,7,4,0),
(22,1,2,8,1,1),
(23,1,2,8,2,1),
(24,1,2,13,1,0),
(25,1,2,13,2,0),
(26,1,2,14,1,1),
(27,1,2,14,2,1),
(28,1,2,15,1,0),
(29,1,2,15,2,0),
(30,1,2,15,3,0),
(31,1,2,15,4,0),
(32,1,2,16,1,0),
(33,1,2,16,2,0),
(34,1,2,17,1,1),
(35,1,2,17,2,1),
(36,1,2,18,1,1),
(37,1,2,19,1,1),
(38,1,2,19,2,1),
(39,1,2,19,3,1),
(40,1,2,19,4,1),
(41,1,2,20,1,1),
(42,1,2,20,2,1),
(43,1,3,1,1,1),
(44,1,3,2,1,0),
(45,1,3,2,2,0),
(46,1,3,2,3,0),
(47,1,3,2,4,0),
(48,1,3,2,5,0),
(49,1,3,2,6,0),
(50,1,3,2,7,0),
(51,1,3,3,1,0),
(52,1,3,3,2,0),
(53,1,3,6,1,1),
(54,1,3,6,2,1),
(55,1,3,6,3,1),
(56,1,3,6,4,1),
(57,1,3,7,1,1),
(58,1,3,8,1,1),
(59,1,3,8,2,1),
(60,1,3,8,3,1),
(61,1,3,13,1,0),
(62,1,3,14,1,1),
(63,1,3,14,2,1),
(64,1,3,15,1,1),
(65,1,3,15,2,0),
(66,1,3,15,3,0),
(67,1,3,15,4,0),
(68,1,3,15,5,0),
(69,1,3,17,1,1),
(70,1,3,17,2,1),
(71,1,3,17,3,1),
(72,1,3,19,1,1),
(73,1,3,19,2,1),
(74,1,3,20,1,1),
(75,1,4,1,1,1),
(76,1,4,2,1,0),
(77,1,4,3,1,0),
(78,1,4,3,2,0),
(79,1,4,3,3,0),
(80,1,4,3,4,0),
(81,1,4,6,1,1),
(82,1,4,6,2,1),
(83,1,4,6,3,1),
(84,1,4,7,1,1),
(85,1,4,7,2,1),
(86,1,4,13,1,0),
(87,1,4,13,2,0),
(88,1,4,15,1,1),
(89,1,4,15,2,1),
(90,1,4,15,3,0),
(91,1,4,17,1,1),
(92,1,4,18,1,1),
(93,1,4,19,1,1),
(94,1,4,20,1,1),
(95,1,5,2,1,0),
(96,1,5,2,2,0),
(97,1,5,2,3,0),
(98,1,5,8,1,1),
(99,1,5,8,2,1),
(100,1,5,13,1,0),
(101,1,5,13,2,0),
(102,1,5,14,1,1),
(103,1,5,15,1,1),
(104,1,5,15,2,1),
(105,1,5,20,1,1),
(106,2,1,11,1,1),
(107,2,2,11,1,1),
(108,2,2,11,2,1),
(109,2,2,11,3,0),
(110,2,2,11,4,0),
(111,2,3,5,1,1),
(112,2,3,11,1,1),
(113,2,3,11,2,0),
(114,2,3,11,3,1),
(115,2,3,11,4,0),
(116,2,3,11,5,0),
(117,2,3,11,6,0),
(118,2,3,11,7,0),
(119,2,4,5,1,1),
(120,2,4,5,2,1),
(121,2,4,9,1,1),
(122,2,4,11,1,0),
(123,2,4,11,2,0),
(124,2,4,11,3,0),
(125,2,4,11,4,1),
(126,2,5,5,1,1),
(127,2,5,5,2,1),
(128,2,5,5,3,1),
(129,2,5,5,4,1),
(130,2,5,9,1,1),
(131,2,5,11,1,1),
(132,2,5,11,2,1),
(133,2,5,11,3,1),
(134,2,5,11,4,1),
(135,2,5,11,5,1),
(136,3,1,10,1,0),
(137,3,2,4,1,1),
(138,3,2,4,2,1),
(139,3,2,4,3,1),
(140,3,2,4,4,0),
(141,3,2,4,5,0),
(142,3,2,10,1,0),
(143,3,2,10,2,0),
(144,3,2,18,1,1),
(145,3,3,4,1,1),
(146,3,3,4,2,1),
(147,3,3,4,3,1),
(148,3,3,4,4,0),
(149,3,3,4,5,0),
(150,3,3,4,6,0),
(151,3,3,4,7,0),
(152,3,3,10,1,0),
(153,3,4,4,1,1),
(154,3,4,4,2,0),
(155,3,4,4,3,0),
(156,3,4,4,4,0),
(157,3,4,10,1,0),
(158,3,4,12,1,0),
(159,3,4,12,2,0),
(160,3,4,18,1,1),
(161,3,5,4,1,1),
(162,3,5,4,2,1),
(163,3,5,4,3,1),
(164,3,5,4,4,1),
(165,3,5,4,5,1),
(166,3,5,4,6,1),
(167,3,5,4,7,1),
(168,3,5,10,1,0),
(169,3,5,10,2,1),
(170,3,5,12,1,1),
(171,3,5,12,2,1),
(172,3,5,18,1,1);

INSERT INTO exercise_descriptor_i18n (fk_exercise_descriptor_id, locale, name) VALUES 
(1,"en_US","Can read a very short, rehearsed statement – e.g. to introduce a speaker, propose a toast"),
(1,"de_DE","Kann ein kurzes, eingeübtes Statement verlesen, um z. B. einen Redner vorzustellen oder einen Toast auszubringen"),
(1,"es_ES","Es capaz de leer un comunicado breve y previamente ensayado; por ejemplo, presentar a un hablante o proponer un brindis"),
(1,"fr_FR","Peut lire un texte très bref et répété, par exemple pour présenter un conférencier, proposer un toast"),
(2,"en_US","Can make an introduction and use basic greeting and leave-taking expressions"),
(2,"de_DE","Kann jemanden vorstellen und einfache Gruß- und Abschiedsformeln gebrauchen"),
(2,"es_ES","Se presenta y utiliza saludos y expresiones de despedida básicos"),
(2,"fr_FR","Peut présenter quelqu'un et utiliser des expressions élémentaires de salutation et de congé"),
(3,"en_US","Can ask how people are and react to news"),
(3,"de_DE","Kann jemanden nach dem Befinden fragen und auf Neuigkeiten reagieren"),
(3,"es_ES","Pregunta cómo están las personas y expresa sus reacciones ante las noticias"),
(3,"fr_FR","Peut demander à quelqu'un de ses nouvelles et y réagir"),
(4,"en_US","Can describe him/herself, what he/she does and where he/she lives"),
(4,"de_DE","Kann sich selbst beschreiben und sagen, was er/sie beruflich tut und wo er/sie wohnt"),
(4,"es_ES","Es capaz de describirse a sí mismo, hablar de su profesión y de su lugar de residencia"),
(4,"fr_FR","Peut se décrire, décrire ce qu'il/elle fait, ainsi que son lieu d'habitation"),
(5,"en_US","CAN ask simple questions of a factual nature and understand the answers provided these are expressed in simple language (for example, 'Where is the dining-room?' 'It's on the first floor', etc.)"),
(5,"de_DE","KANN einfache, sachliche Fragen stellen und die Antworten verstehen, soweit diese in einfacher Sprache gegeben werden (z. B. \"Wo ist der Speisesaal?\" \"Er ist im ersten Stock\" usw.)"),
(5,"es_ES","PUEDE hacer preguntas sencillas, de naturaleza objetiva, y comprender las respuestas siempre que estén expresadas en lenguaje sencillo (por ej. \"¿Dónde está el comedor?\" \"Está en el primer piso.\", etc.)"),
(5,"fr_FR","EST CAPABLE de poser des questions d'ordre pratique et comprendre les réponses si elles sont exprimées dans un langage simple (par exemple, \"Où est la salle à manger ?\" \"Elle est au premier étage\", etc.)"),
(6,"en_US","CAN make simple complaints, for example 'The water is cold'"),
(6,"de_DE","KANN einfache Beschwerden äußern, z. B. \"Das Wasser ist kalt\""),
(6,"es_ES","PUEDE formular quejas sencillas, por ejemplo, \"El agua está fría\""),
(6,"fr_FR","EST CAPABLE de formuler des réclamations simples comme \"L'eau est froide\""),
(7,"en_US","CAN call an emergency number, give location and ask for relevant service"),
(7,"de_DE","KANN eine Notrufnummer anwählen, den Ort angeben und um Hilfe bitten"),
(7,"es_ES","PUEDE llamar por teléfono a un número de emergencia, pedir el servicio que necesite y dar su dirección"),
(7,"fr_FR","EST CAPABLE d'appeler un numéro d'urgence, de donner l'adresse et demander le service requis"),
(8,"en_US","Can tell a story or describe something in a simple list of points"),
(8,"de_DE","Kann etwas erzählen oder in Form einer einfachen Aufzählung berichten"),
(8,"es_ES","Narra historias o describe algo mediante una relación sencilla de elementos"),
(8,"fr_FR","Peut raconter une histoire ou décrire quelque chose par une simple liste de points"),
(9,"en_US","Can describe everyday aspects of his/her environment e.g. people, places, a job or study experience"),
(9,"de_DE","Kann über Aspekte des eigenen alltäglichen Lebensbereichs berichten, z. B. über Leute, Orte, Erfahrungen in Beruf oder Ausbildung"),
(9,"es_ES","Describe aspectos cotidianos de su entorno; por ejemplo, personas, lugares, una experiencia de trabajo o de estudio"),
(9,"fr_FR","Peut décrire les aspects de son environnement quotidien tels que les gens, les lieux, l'expérience professionnelle ou scolaire"),
(10,"en_US","Can give short, basic descriptions of events and activities"),
(10,"de_DE","Kann kurz und einfach über ein Ereignis oder eine Tätigkeit berichten"),
(10,"es_ES","Realiza descripciones breves y básicas de hechos y actividades"),
(10,"fr_FR","Peut faire une description brève et élémentaire d'un événement ou d'une activité "),
(11,"en_US","Can describe plans and arrangements, habits and routines, past activities and personal experiences"),
(11,"de_DE","Kann Pläne und Vereinbarungen, Gewohnheiten und Alltagsbeschäftigungen beschreiben sowie über vergangene Aktivitäten und persönliche Erfahrungen berichten"),
(11,"es_ES","Describe planes y citas, costumbres, actividades habituales o pertenecientes al pasado y experiencias personales"),
(11,"fr_FR","Peut décrire des projets et préparatifs, des habitudes et occupations journalières, des activités passes et des expériences personnelles"),
(12,"en_US","Can use simple descriptive language to make brief statements about and compare objects and possessions"),
(12,"de_DE","Kann mit einfachen Mitteln Gegenstände sowie Dinge, die ihm/ihr gehören, kurz beschreiben und vergleichen"),
(12,"es_ES","Utiliza un lenguaje sencillo y descriptivo para realizar breves declaraciones sobre objetos y posesiones y para hacer comparaciones"),
(12,"fr_FR","Peut décrire et comparer brièvement, dans une langue simple, des objets et choses lui appartenant"),
(13,"en_US","Can explain what he/she likes or dislikes about something"),
(13,"de_DE","Kann erklären, was er/sie an etwas mag oder nicht mag"),
(13,"es_ES","Explica lo que le gusta y lo que no le gusta respecto a algo"),
(13,"fr_FR","Peut expliquer en quoi une chose lui plait ou lui déplaît"),
(14,"en_US","CAN get the attention of staff in an appropriate way and order a meal in a restaurant"),
(14,"de_DE","KANN im Restaurant die Bedienung höflich rufen und ein Essen bestellen"),
(14,"es_ES","PUEDE conseguir la atención de los camareros de manera apropiada y pedir une comida en un restaurante"),
(14,"fr_FR","EST CAPABLE d'attirer correctement l'attention des serveurs et commander un repas"),
(15,"en_US","CAN ask simple questions about the menu and understand simple answers"),
(15,"de_DE","KANN einfache Fragen über die Speisekarte stellen und einfache Antworten verstehen"),
(15,"es_ES","PUEDE hacer preguntas sencillas sobre la carta y comprender respuestas sencillas"),
(15,"fr_FR","EST CAPABLE de poser des questions simples sur le menu et comprendre des réponses simples"),
(16,"en_US","CAN express an opinion about food"),
(16,"de_DE","KANN seine Meinung über das Essen äußern"),
(16,"es_ES","PUEDE expresar de forma muy sencilla une opinión sobre la comida"),
(16,"fr_FR","EST CAPABLE d'exprimer une opinion sur la nourriture"),
(17,"en_US","CAN make simple complaints, for example, 'The food is cold'"),
(17,"de_DE","KANN einfache Beschwerden äußern, z. B. \"Das Essen ist kalt\""),
(17,"es_ES","PUEDE formular quejas muy simples, por ej., \"La comida está fría\""),
(17,"fr_FR","EST CAPABLE de formuler des réclamations simples comme \"Le plat est froid\""),
(18,"en_US","CAN ask for what is required, if it is something which the shopkeeper can readily understand"),
(18,"de_DE","KANN nach dem fragen, was er/sie möchte, wenn der Verkäufer es gleich versteht"),
(18,"es_ES","PUEDE pedir lo que necesita, si es algo que el dependiente puede comprender fácilmente"),
(18,"fr_FR","EST CAPABLE de demander ce qu'il désire s'il s'agit de quelque chose que le vendeur peut comprendre immédiatement"),
(19,"en_US","Can ask about things and make simple transactions in shops, post offices or banks"),
(19,"de_DE","Kann in Geschäften, Postämtern, Banken nach etwas fragen und einfache Erledigungen machen"),
(19,"es_ES","Pregunta sobrecosas y realiza transacciones sencillas en tiendas, oficinas de correo o bancos"),
(19,"fr_FR","Peut poser des questions et effectuer des transactions simples dans un magasin, un bureau de poste, une banque"),
(20,"en_US","Can give and receive information about quantities, numbers, prices, etc."),
(20,"de_DE","Kann Informationen über Mengen, Anzahl, Preise usw. geben und verstehen"),
(20,"es_ES","Ofrece y recibe información relativa a cantidades, números, precios, etc."),
(20,"fr_FR","Peut demander et fournir des renseignements à propos d'une quantité, un nombre, un prix, etc."),
(21,"en_US","Can make simple purchases by stating what is wanted and asking the price"),
(21,"de_DE","Kann einfache Einkäufe machen, sagen, was er/sie sucht, und nach dem Preis fragen"),
(21,"es_ES","Realiza compras sencillas diciendo lo que quiere y preguntando el precio"),
(21,"fr_FR","Peut faire un achat simple en indiquant ce qu'il/elle veut et en demandant le prix"),
(22,"en_US","CAN ask (face-to-face) for a medical appointment and understand the reply"),
(22,"de_DE","KANN persönlich um einen Arzttermin bitten und die Antwort verstehen"),
(22,"es_ES","PUEDE pedir (en persona) hora con el medico y comprender la respuesta"),
(22,"fr_FR","EST CAPABLE de demander (en face à face) un rendez-vous avec le médecin et de comprendre la réponse"),
(23,"en_US","CAN indicate the nature of a problem to a 9 professional, perhaps using gestures and body language"),
(23,"de_DE","KANN einem Arzt eine Beschwerde beschreiben, indem er/ sie möglicherweise Gestik und Körpersprache verwendet"),
(23,"es_ES","PUEDE explicar la naturaleza de un problema a un/a profesional de la salud, apuyándose sobre todo en gestos y lenguaje corporal"),
(23,"fr_FR","EST CAPABLE d'indiquer la nature du problème à un professionnel de la santé en ayant peut être recours aux gestes et aux mimiques"),
(24,"en_US","Can give a short, rehearsed, basic presentation on a familiar subject"),
(24,"de_DE","Kann eine eingeübte, kurze, einfache Präsentation zu einem vertrauten Thema vortragen"),
(24,"es_ES","Realiza presentaciones breves, básicas y ensayadas que versen sobre asuntos cotidianos"),
(24,"fr_FR","Peut faire un bref exposé élémentaire, répété, sur un sujet familier"),
(25,"en_US","Can give a short, rehearsed presentation on a topic pertinent to his/her everyday life, briefly give reasons and explanations for opinions, plans and actions"),
(25,"de_DE","Kann eine kurze, eingeübte Präsentation zu einem Thema aus seinem/ihrem Alltag vortragen und dabei kurz Gründe und Erläuterungen zu Meinungen, Plänen und Handlungen geben"),
(25,"es_ES","Realiza presentaciones breves y ensayadas sobre temas que son de importancia en vida cotidiana y ofrece brevemente motivos y explicaciones para expresar ciertas opiniones, planes y acción"),
(25,"fr_FR","Peut faire un bref exposé préparé sur un sujet relatif à sa vie quotidienne, donner brièvement des justifications et des explications pour ses opinions, ses projets et ses actes"),
(26,"en_US","CAN ask for and understand the required information from a tourist office, provided this is of a familiar, non-specialised nature"),
(26,"de_DE","KANN von einem Fremdenverkehrsamt Informationen erbitten und sie auch verstehen, sofern sie vertraut und nicht zu speziell sind"),
(26,"es_ES","PUEDE pedir y comprender la información que necesita en une oficina de turismo, con tal de que sea de naturaleza familiar y no-especializada"),
(26,"fr_FR","EST CAPABLE de demander et comprendre une information dans un bureau de tourisme si l'information est simple et non spécialisée"),
(27,"en_US","CAN give simple explanations about familiar places"),
(27,"de_DE","KANN einfache Erklärungen zu bekannten Orten geben"),
(27,"es_ES","PUEDE dar explicaciones sencillas sobre lugares familiares"),
(27,"fr_FR","EST CAPABLE de donner des explications simples concernant des lieux connus"),
(28,"en_US","Can establish social contact: greetings and farewells; introductions; giving thanks"),
(28,"de_DE","Kann sozialen Kontakt herstellen durch Begrüßung, Abschied, Sich-Vorstellen, Danken"),
(28,"es_ES","Establece contacto social: saludos y despedidas; presentaciones; agradecimientos"),
(28,"fr_FR","Peut établir un contact social: salutations et congé; remerciements ; présentations"),
(29,"en_US","Can express how he/she feels in simple terms, and express thanks"),
(29,"de_DE","Kann in einfachen Worten sagen, wie es ihm/ihr geht, und Dank ausdrücken"),
(29,"es_ES","Expresa cómo se siente en términos sencillos y sabe cómo dar las gracias "),
(29,"fr_FR","Peut dire en termes simples comment il/elle va et remercier"),
(30,"en_US","Can make and respond to invitations, suggestions and apologies"),
(30,"de_DE","Kann jemanden einladen und auf Einladungen reagieren und kann um Entschuldigung bitten und auf Entschuldigungen reagieren"),
(30,"es_ES","Realiza invitaciones y sugerencias, y responde a las que le hacen; se disculpa y responde a las disculpas que le presentan"),
(30,"fr_FR","Peut faire et accepter une offre, une invitation et des excuses"),
(31,"en_US","Can say what he/she likes and dislikes"),
(31,"de_DE","Kann sagen, was er/sie gerne hat und was nicht"),
(31,"es_ES","Sabe expresar lo que le gusta y lo que no le gusta"),
(31,"fr_FR","Peut dire ce qu'il/elle aime ou non"),
(32,"en_US","Can describe his/her family, living conditions, educational background, present or most recent job"),
(32,"de_DE","Kann die Familie, Lebensverhältnisse, die Ausbildung und die gegenwärtige oder die letzte berufliche Tätigkeit beschreiben"),
(32,"es_ES","Describe a su familia, sus condiciones de vida, sus estudios y su trabajo actual, o el último que tuvo"),
(32,"fr_FR","Peut décrire sa famille, ses conditions de vie, sa formation, son travail actuel ou le dernier en date"),
(33,"en_US","Can describe people, places and possessions in simple terms"),
(33,"de_DE","Kann mit einfachen Worten Personen, Orte, Dinge beschreiben"),
(33,"es_ES","Describe personas, lugares y posesiones en términos sencillos"),
(33,"fr_FR","Peut décrire les gens, lieux et choses en termes simples"),
(34,"en_US","CAN book a room (face-to-face) in a hotel, bed and breakfast, etc."),
(34,"de_DE","KANN persönlich ein Zimmer in einem Hotel, einer Pension usw. buchen"),
(34,"es_ES","PUEDE reservar en persona una habitación en un hotel, pensión, etc."),
(34,"fr_FR","EST CAPABLE de demander (en face à face) une chambre dans un hôtel ou en chambre d'hôte"),
(35,"en_US","CAN make a complaint about simple matters, for example 'The light in my room doesn't work.'"),
(35,"de_DE","KANN sich über einfache Sachverhalte beschweren, z. B. \"Das Licht in meinem Zimmer funktioniert nicht.\""),
(35,"es_ES","PUEDE formular una queja sobre asuntos sencillos, por ejemplo, \"La luz de mi habitación no funciona.\""),
(35,"fr_FR","EST CAPABLE de formuler une réclamation simple, par exemple \"La lumière ne marche pas dans ma chambre\""),
(36,"en_US","CAN participate in a simple phone conversation with a known person on a predictable topic, e.g. 21 arrangements"),
(36,"de_DE","KANN sich an einem einfachen Telefongespräch mit einer bekannten Person über ein vorhersehbares Thema beteiligen, wie etwa Reisevorbereitungen"),
(36,"es_ES","PUEDE participar en una conversación telefónica sencilla con una persona conocida sobre un tema previsible, por ej., los preparativos de un viaje"),
(36,"fr_FR","EST CAPABLE de soutenir une conversation téléphonique avec une personne connue sur un sujet convenu comme les préparatifs d'un voyage"),
(37,"en_US","CAN, on arrival in a foreign country, answer routine questions such as 'How long are you staying?' and respond appropriately to instructions such as 'Open your suitcase', etc."),
(37,"de_DE","KANN bei Ankunft in einem fremden Land alltägliche Fragen beantworten wie \"Wie lange bleiben Sie?\" und Anweisungen wie \"Öffnen Sie Ihren Koffer\" usw. Befolgen"),
(37,"es_ES","PUEDE, al llegar a un país extranjero, contestar a preguntas rutinarias como \"¿Cuánto tiempo va a quedarse?\" y responder apropiadamente a indicaciones como \"Abra su maleta\" etc."),
(37,"fr_FR","EST CAPABLE, en arrivant dans un pays étranger, de répondre aux questions courantes du type \"Combien de jours resterez-vous ?\" et réagir de manière adéquate aux instructions du type \"Ouvrez votre valise\""),
(38,"en_US","CAN give and understand straightforward directions, provided that these are not lengthy and/or complex"),
(38,"de_DE","KANN klare Wegweisungen geben und verstehen, solange diese nicht lang und/oder kompliziert sind"),
(38,"es_ES","PUEDE dar y comprender direcciones sencillas, siempre que no sean demasiado extensas ni complejas"),
(38,"fr_FR","EST CAPABLE de donner et comprendre des indications simples si elles ne sont pas longues et/ou compliquées"),
(39,"en_US","CAN go to a 21 information centre at, for example, a railway/bus station and ask for information as to how to get from A to B"),
(39,"de_DE","KANN zur Reiseauskunft z. B. am Bahnhof/Busbahnhof gehen und sich erkundigen, wie man von A nach B fährt"),
(39,"es_ES","PUEDE pedir información en une estación de tren o autobús, y preguntar por ejemplo cómo llegar de A a B"),
(39,"fr_FR","EST CAPABLE d'aller dans un centre d'information sur des voyages, par exemple une gare ferroviaire ou routière et demander comment se rendre d'un lieu à un autre"),
(40,"en_US","CAN ask to book tickets"),
(40,"de_DE","KANN um die Buchung einer Fahrkarte bitten"),
(40,"es_ES","PUEDE hacer una reserva de billetes"),
(40,"fr_FR","EST CAPABLE de réserver des billets"),
(41,"en_US","CAN ask for simple post office services (e.g. 'I want to send this to Oman', 'One first class stamp, please')"),
(41,"de_DE","KANN um einfache Postdienste bitten (z. B. \"Ich möchte das nach Japan schicken\", \"Eine Briefmarke für einen Euro, bitte.\")"),
(41,"es_ES","PUEDE solicitar servicios postales muy sencillos (por ej., \"Quiero enviar esto a Omán\" o \"Un sello de primera clase, por favor\")"),
(41,"fr_FR","EST CAPABLE de demander des services simples dans un bureau de poste (\"Je voudrais envoyer ceci à Oman\", \"Un timbre, au tarif normal, S.V.P.\")"),
(42,"en_US","CAN ask to change money at a bank (e.g. 'Can I change these here?')"),
(42,"de_DE","KANN bei einer Bank Geld wechseln lassen ( z. B. \"Kann ich das hier wechseln?\")"),
(42,"es_ES","PUEDE solicitar el cambio de dinero en un banco (por ej., \"¿Puedo cambiar esto aquí?\")"),
(42,"fr_FR","EST CAPABLE de demander de changer des devises dans une banque, (de dire par exemple, \"Est-ce que je peux changer cet argent ici ?)"),
(43,"en_US","CAN indicate nature of problem and understand simple instructions and questions"),
(43,"de_DE","KANN die Art des Notfalls angeben sowie einfache Anweisungen und Fragen verstehen"),
(43,"es_ES","PUEDE indicar la naturaleza del problema y comprender preguntas e instrucciones sencillas"),
(43,"fr_FR","EST CAPABLE d'indiquer la nature du problème et de comprendre des questions et des instructions simples"),
(44,"en_US","Can give straightforward descriptions on a variety of familiar subjects within his/her field of interest"),
(44,"de_DE","Kann zu verschiedenen vertrauten Themen des eigenen Interessenbereichs unkomplizierte Beschreibungen oder Berichte geben"),
(44,"es_ES","Realiza descripciones sencillas sobre une variedad de asuntos habituales dentro de su especialidad"),
(44,"fr_FR","Peut faire une description directe et simple de sujets familiers variés dans le cadre de son domaine d'intérêt"),
(45,"en_US","Can reasonably fluently relate a straightforward narrative or description as a linear sequence of points"),
(45,"de_DE","Kann relativ flüssig unkomplizierte Geschichten oder Beschreibungen wiedergeben, indem er/sie die einzelnen Punkte linear aneinander reiht"),
(45,"es_ES","Realiza con razonable fluidez narraciones o descripciones sencillas siguiendo una secuencia lineal de elementos"),
(45,"fr_FR","Peut rapporter assez couramment une narration ou une description simple sous forme d'une suite de points"),
(46,"en_US","Can give detailed accounts of experiences, describing feelings and reactions"),
(46,"de_DE","Kann detailliert über eigene Erfahrungen berichten und dabei die eigenen Gefühle und Reaktionen beschreiben"),
(46,"es_ES","Realiza relaciones detalladas de experiencias describiendo sentimientos y reacciones"),
(46,"fr_FR","Peut relater en détail ses expériences en décrivant ses sentiments et ses réactions"),
(47,"en_US","Can relate details of unpredictable occurrences, e.g. an accident"),
(47,"de_DE","Kann über die wichtigsten Einzelheiten eines unvorhergesehenen Ereignisses (z. B. eines Unfalls) berichten"),
(47,"es_ES","Relata los detalles de acontecimientos impredecibles, como, por ejemplo, un accidente"),
(47,"fr_FR","Peut relater les détails essentiels d'un événement fortuit, tel un accident "),
(48,"en_US","Can relate the plot of a book or film and describe his/her reactions"),
(48,"de_DE","Kann die Handlung eines Films oder eines Buchs wiedergeben und die eigenen Reaktionen beschreiben"),
(48,"es_ES","Relata argumentos de libros o películas y describe sus reacciones"),
(48,"fr_FR","Peut raconteur l'intrigue d'un livre ou d'un film et décrire ses propres réactions"),
(49,"en_US","Can describe dreams, hopes and ambitions"),
(49,"de_DE","Kann Träume, Hoffnungen, Ziele beschreiben"),
(49,"es_ES","Describe sueños, esperanzas y ambiciones"),
(49,"fr_FR","Peut décrire un rêve, un espoir ou une ambition"),
(50,"en_US","Can describe events, real or imagined"),
(50,"de_DE","Kann reale und erfundene Ereignisse schildern"),
(50,"es_ES","Describe hechos reales o imaginados"),
(50,"fr_FR","Peut décrire un événement, réel ou imaginaire"),
(51,"en_US","Can develop an argument well enough to be followed without difficulty most of the time"),
(51,"de_DE","Kann eine Argumentation gut genug ausführen, um die meiste Zeit ohne Schwierigkeiten verstanden zu werden"),
(51,"es_ES","Desarrolla argumentos lo bastante bien como para que se puedan comprender sin dificultad la mayor parte del tiempo"),
(51,"fr_FR","Peut développer une argumentation suffisamment bien pour être compris sans difficulté la plupart du temps"),
(52,"en_US","Can briefly give reasons and explanations for opinions, plans and actions"),
(52,"de_DE","Kann für Ansichten, Pläne oder Handlungen kurze Begründungen oder Erklärungen geben"),
(52,"es_ES","Ofrece breves razonamientos y explicaciones de opiniones, planes y acciones"),
(52,"fr_FR","Peut donner brièvement raisons et explications relatives à des opinions, projets et actions"),
(53,"en_US","CAN order a meal in a restaurant"),
(53,"de_DE","KANN eine Mahlzeit in einem Restaurant bestellen"),
(53,"es_ES","PUEDE pedir la comida en un restaurant"),
(53,"fr_FR","EST CAPABLE de commander un repas dans un restaurant"),
(54,"en_US","CAN ask basic questions about the food in relation to the menu, and about the services available (e.g. use of credit cards, availability of high-chairs or half-portions for children)"),
(54,"de_DE","KANN einfache Fragen zur Speisekarte und zu besonderen Wünschen (z.B. Bezahlung mit Kreditkarte, Fragen zu Kindermenüs, etc.) stellen"),
(54,"es_ES","PUEDE hacer preguntas básicas sobre la comida en relación a la carta, y cobre los servicios disponibles (por ej., el uso de tarjetas de crédito, disponibilidad de sillas especiales para niños pequeños, o porciones más pequeñas para niños)"),
(54,"fr_FR","EST CAPABLE de poser des questions simples sur la nourriture en rapport avec le menu et sur la possibilité de certains services (utilisation de cartes de crédit, possibilité de chaises hautes et de demi-portions pour les enfants)"),
(55,"en_US","CAN ask basic questions about the food and understand most explanations that are likely to be given in such establishments (e.g. when a vegetarian or someone keeping dietary laws or forbidden certain foods for medical reasons has to check the contents of a dish)"),
(55,"de_DE","KANN einfache Fragen über das Essen stellen und einfache Erklärungen auf seine Fragen verstehen (z.B. ein Vegetarier oder jemand, der eine bestimmte Diät einhalten muß und wissen möchte, was in dem Essen ist)"),
(55,"es_ES","PUEDE hacer preguntas básicas sobre la comida y comprender la mayoría de la explicaciones que pueden darse en tales establecimientos (por ej., cuando un vegetariano o alguien que tiene que seguir un régimen especial por razones de salud o religión tiene que averiguar el contenido de un plato).  "),
(55,"fr_FR","EST CAPABLE de poser des questions simples sur la nourriture et comprendre la plupart des explications qui peuvent être données dans de tels établissements (par exemple quand un végétarien ou une personne au régime, pour raisons médicales ou non, doit vérifier la composition du plat)"),
(56,"en_US","CAN make a complaint about straightforward matters, for example, the service or the bill"),
(56,"de_DE","KANN einfache Beschwerden äußern, zum Beispiel über die Dienstleistung oder die Rechnung"),
(56,"es_ES","PUEDE quejarse de cosas sencillas, por ej., del servicio o de la cuenta"),
(56,"fr_FR","EST CAPABLE de se plaindre de choses simples, par exemple du service ou de l'addition"),
(57,"en_US","CAN go to a counter service shop and ask for most of what (s)he wants"),
(57,"de_DE","KANN in ein Geschäft mit Thekenbedienung gehen und das meiste verlangen, was er/sie möchte"),
(57,"es_ES","PUEDE ir a una tienda y pedir prácticamente todo lo que quiere.  "),
(57,"fr_FR","EST CAPABLE d'aller dans un petit commerce et demander l'essentiel de ce qu'il veut"),
(58,"en_US","CAN ask over the phone for a medical appointment and understand the reply"),
(58,"de_DE","KANN telefonisch um einen Arzttermin bitten und die Antwort verstehen"),
(58,"es_ES","PUEDE pedir hora con el medico por teléfono y comprender la respuesta"),
(58,"fr_FR","EST CAPABLE de demander un rendez-vous avec le médecin et comprendre la réponse"),
(59,"en_US","CAN explain what is wrong in straightforward terms at a chemist's, doctor's, hospital or dentist's, especially if symptoms are visible"),
(59,"de_DE","KANN seine/ihre Symptome mit einfachen, alltäglichen Worten beim Apotheker, im Krankenhaus, beim Arzt oder beim Zahnarzt erklären"),
(59,"es_ES","PUEDE explicar sus síntomas en lenguaje cotidiano en la farmacia, la consulta del médico o del dentista y en el hospital"),
(59,"fr_FR","EST CAPABLE de décrire ses symptômes dans un langage simple chez un pharmacien, à l'hôpital, chez le médecin ou chez le dentiste"),
(60,"en_US","CAN ask for advice and understand the answer, provided this is given in everyday language"),
(60,"de_DE","KANN um Rat fragen und die Antwort verstehen, solange sie in Alltagssprache gegeben wird"),
(60,"es_ES","PUEDE pedir un consejo y comprender la respuesta, siempre que ésta se exprese en lenguaje cotidiano"),
(60,"fr_FR","EST CAPABLE de demander un avis et comprendre la réponse si elle est exprimée en langage courant"),
(61,"en_US","Can give a prepared straightforward presentation on a familiar topic within his/her field which is clear enough to be followed without difficulty most of the time, and in which the main points are explained with reasonable precision"),
(61,"de_DE","Kann eine vorbereitete, unkomplizierte Präsentation zu einem vertrauten Thema aus seinem/ihrem Fachgebiet so klar vortragen, dass man ihr meist mühelos folgen kann, wobei die Hauptpunkte hinreichend präzise erläutert werden"),
(61,"es_ES","Es capaz de hacer una presentación breve y preparada sobre un tema dentro de su especialidad con la suficiente claridad como para que se pueda seguir sin dificultad la mayor parte del tiempo y cuyas ideas principales están explicadas con una razonable precisión"),
(61,"fr_FR","Peut faire un exposé simple et direct, préparé, sur un sujet familier dans son domaine qui soit assez clair pour être suivi sans difficulté la plupart du temps et dans lequel les points importants soient expliqués avec assez de précision"),
(62,"en_US","CAN give simple information to a visitor about familiar places, for example her/his own school, city etc."),
(62,"de_DE","KANN einem Besucher einfache Informationen über bekannte Orte geben, z. B. seine/ihre Schule, Stadt usw."),
(62,"es_ES","PUEDE dar información sencilla a un/a visitante sobre lugares familiares, por ejemplo, su propia escuela o cuidad, etc."),
(62,"fr_FR","EST CAPABLE de donner des informations simples à un visiteur concernant des endroits connus, par exemple, son école, sa ville etc."),
(63,"en_US","CAN answer simple, predictable questions"),
(63,"de_DE","KANN einfache, vorhersehbare Fragen beantworten"),
(63,"es_ES","PUEDE contestar preguntas sencillas y previsibles"),
(63,"fr_FR","EST CAPABLE de répondre à des questions simples et prévisibles"),
(64,"en_US","CAN participate in a conversation in a casual or semi-formal situation for a short time"),
(64,"de_DE","KANN sich an einem Gespräch in einer privaten oder halbformellen Situation für kurze Zeit beteiligen"),
(64,"es_ES","PUEDE participar en una conversación informal o semi-formal durante un tiempo breve"),
(64,"fr_FR","EST CAPABLE de participer à une conversation à bâtons rompus ou semi formelle durant une courte période de temps"),
(65,"en_US","Can compare and contrast alternatives, discussing what to do, where to go, who or which to choose, etc."),
(65,"de_DE","Kann in Gesprächen darüber, was man tun, wohin man gehen oder was man auswählen sollte, Vergleiche anstellen und verschiedene Möglichkeiten einander gegenüberstellen"),
(65,"es_ES","Compara y contrasta alternativas, discutiendo qué hacer, adónde ir, qué o a quién elegir, etc."),
(65,"fr_FR","Peut comparer et opposer des alternatives en discutant de ce qu'il faut faire, où il faut aller, qui désigner, qui ou quoi choisir, etc."),
(66,"en_US","Can enter unprepared into conversations on familiar topics"),
(66,"de_DE","Kann ohne Vorbereitung an Gesprächen über vertraute Themen teilnehmen "),
(66,"es_ES","Aborda de forma improvisada conversaciones que tratan asuntos cotidianos "),
(66,"fr_FR","Peut aborder sans préparation une conversation sur un sujet familier"),
(67,"en_US","Can maintain a conversation or discussion but may sometimes be difficult to follow when trying to say exactly what he/she would like to"),
(67,"de_DE","Kann ein Gespräch oder eine Diskussion aufrechterhalten, ist aber möglicherweise manchmal schwer zu verstehen, wenn er/sie versucht, genau auszudrücken, was er/sie sagen möchte"),
(67,"es_ES","Mantiene una conversación o una discusión, pero a veces resulta difícil entenderle cuando intenta expresar lo que quiere decir"),
(67,"fr_FR","Peut soutenir une conversation ou une discussion mais risqué d'être quelquefois difficile à suivre lorsqu'il/elle essaie de formuler exactement ce qu'il/elle aimerait dire"),
(68,"en_US","Can express and respond to feelings such as surprise, happiness, sadness, interest and indifference"),
(68,"de_DE","Kann Gefühle wie Überraschung, Freude, Trauer, Interesse und Gleichgültigkeit ausdrücken und auf entsprechende Gefühlsäußerungen reagieren"),
(68,"es_ES","Sabe expresar y responder a sentimientos como la sorpresa, la felicidad, la tristeza, el interés y la indiferencia"),
(68,"fr_FR","Peut réagir à des sentiments tels que la surprise, la joie, la tristesse, la curiosité et l'indifférence et peut les exprimer"),
(69,"en_US","CAN book a room in a hotel over the phone"),
(69,"de_DE","KANN ein Hotelzimmer telefonisch buchen"),
(69,"es_ES","PUEDE reservar una habitación de hotel por teléfono"),
(69,"fr_FR","EST CAPABLE de demander une chambre d'hôtel par téléphone"),
(70,"en_US","CAN establish to his/her own satisfaction that the accommodation on offer fulfils all his/her needs"),
(70,"de_DE","KANN feststellen, ob die angebotene Unterkunft seinen/ihren Bedürfnissen entspricht"),
(70,"es_ES","PUEDE determinar si el alojamiento que se ofrece satisfice todas sus necesidades"),
(70,"fr_FR","EST CAPABLE de dire que la chambre proposée lui convient"),
(71,"en_US","CAN deal with most situations likely to arise in a hotel, such as messages, ordering, etc"),
(71,"de_DE","KANN die meisten Situationen bewältigen, die in einem Hotel oft auftreten, wie Nachrichten hinterlassen oder empfangen, etwas bestellen usw."),
(71,"es_ES","PUEDE desenvolverse en la mayor parte de las situaciones predecibles que pueden surgir en un hotel, como recados, pedidos, etc."),
(71,"fr_FR","EST CAPABLE de faire face aux situations qui peuvent se présenter dans un hôtel (messages, commandes, etc.)"),
(72,"en_US","CAN go to a rental firm and ask to hire a car, boat etc."),
(72,"de_DE","KANN zu einer Vermiet-Agentur gehen und ein Auto, Boot usw. Mieten"),
(72,"es_ES","PUEDE ir a una empresa de alquiler de vehículos y alquilar un coche, un barco, etc."),
(72,"fr_FR","EST CAPABLE de se présenter à une agence de location et demander à louer une voiture/un bateau, etc."),
(73,"en_US","CAN deal with most routine situations likely to arise when either making 21 arrangements through a 21 agent or when actually travelling (e.g. buying tickets, checking in at an airport)"),
(73,"de_DE","KANN die meisten alltäglichen Situationen bewältigen, die normalerweise auftreten, wenn man eine Reise über ein Reisebüro bucht oder wenn man reist (z. B. Fahrkarten kaufen, am Flughafen einchecken)"),
(73,"es_ES","PUEDE hacer frente a la mayoría de las situaciones rutinarias que pueden surgir al hacer los preparativos del viaje a través de une agencia de viajes o cuando ya está viajando (por ej., comprar billetes, facturar las maletas en el aeropuerto, etc.)"),
(73,"fr_FR","EST CAPABLE de faire face aux situations pouvant se présenter dans l'organisation d'un voyage avec une agence ou se présentant pendant un voyage (achat des billets, enregistrement à l'aéroport)"),
(74,"en_US","CAN ask to open an account at a bank provided that the procedure is straightforward"),
(74,"de_DE","KANN ein Konto bei einer Bank eröffnen, sofern der Vorgang leicht verständlich ist"),
(74,"es_ES","PUEDE solicitar en términos muy simples abrir une cuenta bancaria siempre que el procedimiento sea sencillo"),
(74,"fr_FR","EST CAPABLE de demander d'ouvrir un compte dans une banque si la procédure est simple"),
(75,"en_US","CAN give a report of an emergency incident, e.g. describe the circumstances of a theft to the police, give details of vehicle breakdown"),
(75,"de_DE","KANN über einen Notfall berichten, d.h. z. B. die Umstände eines Diebstahls der Polizei beschreiben, bei einer Autopanne Einzelheiten angeben"),
(75,"es_ES","PUEDE hacer un informe sobre la situación o el incidente ocurrido, por ej., describir las circunstancias de un robo a la policía, dar detalles sobre la avería de un vehículo"),
(75,"fr_FR","EST CAPABLE de faire un compte rendu en cas d'urgence, par exemple décrire les circonstances d'un vol à la police, donner des informations détaillées sur une panne de voiture"),
(76,"en_US","Can give clear, detailed descriptions on a wide range of subjects related to his/her field of interest"),
(76,"de_DE","Kann im Rahmen des eigenen Interessengebiets zu einem breiten Themenspektrum klare und detaillierte Beschreibungen und Berichte geben"),
(76,"es_ES","Realiza descripciones claras y detalladas sobre una amplia gama de temas relacionados con su especialidad"),
(76,"fr_FR","Peut faire une description claire et détaillée d'une gamme étendue de sujets en relation avec son domaine d'intérêt"),
(77,"en_US","Can develop an argument systematically with appropriate highlighting of significant points, and relevant  supporting detail"),
(77,"de_DE","Kann etwas systematisch erörtern und dabei entscheidende Punkte in angemessener Weise hervorheben und stützende Einzelheiten anführen"),
(77,"es_ES","Desarrolla argumentos sistemáticamente, dando un énfasis apropiado a los aspectos importantes y apoyándose en detalles adecuados"),
(77,"fr_FR","Peut développer méthodiquement une argumentation en mettant en évidence les points significatifs et les éléments pertinents"),
(78,"en_US","Can develop a clear argument, expanding and supporting his/her points of view at some length with subsidiary points and relevant examples"),
(78,"de_DE","Kann etwas klar erörtern, indem er/sie die eigenen Standpunkte ausführlich darstellt und durch Unterpunkte oder geeignete Beispiele stützt"),
(78,"es_ES","Desarrolla argumentos con claridad, ampliando con cierta extensión y defendiendo sus puntos de vista con ideas complementarias y ejemplos adecuados"),
(78,"fr_FR","Peut développer une argumentation claire, en élargissant et confirmant ses points de vue par des arguments secondaires et des exemples pertinents"),
(79,"en_US","Can construct a chain of reasoned argument"),
(79,"de_DE","Kann seine/ihre Argumentation logisch aufbauen und verbinden"),
(79,"es_ES","Construye cadenas argumentales razonadas"),
(79,"fr_FR","Peut enchaîner des arguments avec logique"),
(80,"en_US","Can explain a viewpoint on a topical issue giving the advantages and disadvantages of various options"),
(80,"de_DE","Kann den Standpunkt zu einem Problem erklären und die Vor- und Nachteile verschiedener Alternativen angeben"),
(80,"es_ES","Explica puntos de vista sobre un tema, proponiendo las ventajas y las desventajas de varias opciones"),
(80,"fr_FR","Peut expliquer un point de vue sur un problème en donnant les avantages et les inconvénients d'options diverses"),
(81,"en_US","CAN order a meal and ask for clarification about dishes on the menu"),
(81,"de_DE","KANN ein Essen bestellen und sich die Speisen auf der Karte erklären lassen"),
(81,"es_ES","PUEDE pedir una comida y solicitar aclaraciones sobre la carta"),
(81,"fr_FR","EST CAPABLE de commander un repas et demander des éclaircissements sur des plats au menu"),
(82,"en_US","CAN maintain an interaction related to the nature and quality of the food"),
(82,"de_DE","KANN sich über die Art und Qualität des Essens äußern"),
(82,"es_ES","PUEDE mantener une interacción relacionada con las características y la calidad de la comida.  "),
(82,"fr_FR","EST CAPABLE de maintenir une conversation sur la nature et la qualité de la nourriture"),
(83,"en_US","CAN complain effectively about most situations that are likely to arise in a restaurant"),
(83,"de_DE","KANN sich über die meisten Situationen, die häufig in einem Restaurant vorkommen, erfolgreich beschweren"),
(83,"es_ES","PUEDE quejarse eficazmente de la mayoría de las situaciones que pueden surgir en un restaurante"),
(83,"fr_FR","EST CAPABLE de se plaindre dans la plupart des situations qui peuvent se présenter dans un restaurant"),
(84,"en_US","CAN ask effectively for refund or exchange of faulty or unwanted goods"),
(84,"de_DE","KANN erfolgreich um Vergütung oder Umtausch defekter oder unerwünschter Ware bitten"),
(84,"es_ES","PUEDE pedir con eficacia el cambio o devolución de mercancías dañadas o que no quiere aceptar"),
(84,"fr_FR","EST CAPABLE de demander l'échange ou le remboursement d'une marchandise défectueuse ou qu'il ne désire plus"),
(85,"en_US","CAN bargain for what (s)he wants and reach an agreement"),
(85,"de_DE","KANN über den Preis von dem, was er/sie möchte, verhandeln und sich einigen"),
(85,"es_ES","PUEDE regatear para conseguir lo que quiere y llegar a un acuerdo"),
(85,"fr_FR","EST CAPABLE de marchander et conclure un accord"),
(86,"en_US","Can give a clear, prepared presentation, giving reasons in support of or against a particular point of view and giving the advantages and disadvantages of various options"),
(86,"de_DE","Kann eine klare, vorbereitete Präsentation vortragen und dabei Gründe für oder gegen einen Standpunkt anführen und die Vor- und Nachteile verschiedener Alternativen angeben"),
(86,"es_ES","Realiza con claridad presentaciones preparadas previamente, razonando a favor o en contra de un punto de vista concreto, y mostrando las ventajas y desventajas de varias opciones"),
(86,"fr_FR","Peut développer un exposé de manière claire et méthodique en soulignant les points significatifs et les éléments pertinents"),
(87,"en_US","Can give a clear, systematically developed presentation, with highlighting of significant points, and relevant supporting detail"),
(87,"de_DE","Kann eine klare und systematisch angelegte Präsentation vortragen und dabei wesentliche Punkte und relevante unterstützende Details hervorheben"),
(87,"es_ES","Realiza presentaciones claras y desarrolladas sistemáticamente, poniendo énfasis en los aspectos significativos y ofreciendo detalles relevantes que sirvan de apoyo"),
(87,"fr_FR","Peut faire un exposé clair, préparé, en avançant des raisons pour ou contre un point de vue particulier et en présentant les avantages et les inconvénients d'options diverses "),
(88,"en_US","CAN keep up a conversation on a fairly wide range of topics, e.g. personal and professional experiences, events currently in the news"),
(88,"de_DE","KANN ein Gespräch über eine relativ breite Auswahl von Themen aufrechterhalten, z.B. persönliche und berufliche Erfahrungen oder aktuelle Ereignisse in den Nachrichten"),
(88,"es_ES","PUEDE mantener una conversación sobre un agama bastante amplia de temas, por ej., las experiencias personales  y profesionales, temas de actualidad, etc."),
(88,"fr_FR","EST CAPABLE de soutenir une conversation sur un grand éventail de sujets, comme les expériences personnelles ou professionnelles, les faits d'actualité"),
(89,"en_US","CAN express opinions on abstract/cultural matters, and defend them"),
(89,"de_DE","KANN seine/ihre Meinung über abstrakte/kulturelle Themen äußern und verteidigen"),
(89,"es_ES","PUEDE expresar opiniones sobre temas abstractos/culturales y defenderlas"),
(89,"fr_FR","EST CAPABLE d'exprimer des opinions sur des sujets abstraits/culturels et de les défendre"),
(90,"en_US","Can convey degrees of emotion and highlight the personal significance of events and experiences"),
(90,"de_DE","Kann verschieden starke Gefühle zum Ausdruck bringen und die persönliche Bedeutung von Ereignissen und Erfahrungen hervorheben"),
(90,"es_ES","Transmite cierta emoción y resalta la importancia personal de hechos y experiencias"),
(90,"fr_FR","Peut transmettre différents degrés d'émotion et souligner ce qui est important pour lui/elle dans un événement ou une expérience"),
(91,"en_US","CAN argue/complain effectively about most problem areas that are likely to occur"),
(91,"de_DE","KANN erfolgreich über die meisten Probleme, die häufig auftreten, argumentieren/sich beschweren"),
(91,"es_ES","PUEDE discutir/quejarse eficazmente en las situaciones problemáticas que pueden surgir con más frecuencia"),
(91,"fr_FR","EST CAPABLE de réclamer et d'argumenter concernant la plupart des problèmes qui peuvent se présenter"),
(92,"en_US","CAN participate in casual conversation over the phone with a known person on a variety of topics"),
(92,"de_DE","KANN an einem informellen Telefongespräch mit einer bekannten Person über viele verschiedene Themen teilnehmen"),
(92,"es_ES","PUEDE participar en una conversación telefónica informal con una persona conocida sobre diversos temas"),
(92,"fr_FR","EST CAPABLE de soutenir une conversation téléphonique familière avec une personne connue sur une variété de sujets"),
(93,"en_US","CAN deal with all kinds of 21 arrangements and travelling"),
(93,"de_DE","KANN jede Form von Reisevorbereitungen und Reisen bewältigen"),
(93,"es_ES","PUEDE ocuparse de todo tipo de preparativos antes de un viaje y durante el viaje"),
(93,"fr_FR","EST CAPABLE de s'occuper de tous les préparatifs d'un voyage et du voyage lui-même"),
(94,"en_US","CAN ask questions related to different types of post office services and understand answers if sympathetically expressed"),
(94,"de_DE","KANN Fragen bezüglich der verschiedenen Postdienste stellen und Antworten verstehen, die einfühlend ausgedrückt werden"),
(94,"es_ES","PUEDE formular preguntas relacionadas con los diferentes tipos de servicios postales y comprender las respuestas si éstas intentan adaptarse a sus dificultades con el idioma"),
(94,"fr_FR","EST CAPABLE de poser des questions concernant les différents services proposés par la poste et comprendre les réponses si elles sont exprimées clairement"),
(95,"en_US","Can give clear, detailed descriptions of complex subjects"),
(95,"de_DE","Kann komplexe Sachverhalte klar und detailliert darstellen"),
(95,"es_ES","Realiza descripciones claras y detalladas de temas complejos"),
(95,"fr_FR","Peut faire une description claire et détaillée de sujets complexes"),
(96,"en_US","Can give elaborate descriptions and narratives, integrating sub-themes, developing particular points and rounding off with an appropriate conclusion"),
(96,"de_DE","Kann Sachverhalte ausführlich beschreiben und Geschichten erzählen, kann untergeordnete Themen integrieren, bestimmte Punkte genauer ausführen und alles mit einem angemessenen Schluss abrunden"),
(96,"es_ES","Realiza descripciones y narraciones complejas integrando otros temas, desarrollando aspectos concretos y terminando con une conclusión adecuada"),
(96,"fr_FR","Peut faire une description ou une narration élaborée, en y intégrant des thèmes secondaires, en développant certains points et en terminant par une conclusion appropriée"),
(97,"en_US","Can give clear, smoothly flowing, elaborate and often memorable descriptions"),
(97,"de_DE","Kann Sachverhalte klar, flüssig, ausführlich und oft sehr interessant darstellen"),
(97,"es_ES","Realiza descripciones claras, fluidas, elaboradas y a menudo destacables"),
(97,"fr_FR","Peut faire des descriptions limpides et courantes, élaborées et souvent mémorables"),
(98,"en_US","CAN enquire effectively about 9 services provided, entitlements and procedures involved"),
(98,"de_DE","KANN sich erfolgreich über angebotene Gesundheitsleistungen, Ansprüche und Verfahren erkundigen"),
(98,"es_ES","PUEDE informarse eficazmente sobre los servicios de salud disponibles y sobre sus derechos y los procedimientos implicados"),
(98,"fr_FR","EST CAPABLE de poser des questions sur les différents services de santé proposés, ses droits et les procédures à suivre"),
(99,"en_US","CAN describe non-visible symptoms such as different kinds of pain, for example 'dull', 'stabbing', 'throbbing' etc."),
(99,"de_DE","KANN unsichtbare Symptome sowie verschiedene Arten von Schmerzen beschreiben, zum Beispiel \"dumpf\", \"stechend\", \"pochend\""),
(99,"es_ES","PUEDE describir síntomas que no están a la vista, como por ej. Diferentes tipos de dolor: \"punzante\", \"palpitante\", \"apagado\""),
(99,"fr_FR","EST CAPABLE de décrire des symptômes non visibles tels que des douleurs de type différent comme \"sourde\", \"lancinante\", \"élancée\""),
(100,"en_US","Can give a clear, well-structured presentation of a complex subject, expanding and supporting points of view at some length with subsidiary points, reasons and relevant examples"),
(100,"de_DE","Kann ein komplexes Thema gut strukturiert und klar vortragen und dabei die eigenen Standpunkte ausführlich darstellen und durch Unterpunkte, geeignete Beispiele oder Begründungen stützen"),
(100,"es_ES","Realiza presentaciones claras y bien estructuradas sobre un tema complejo, ampliando con cierta extensión y defendiendo sus puntos de vista con ideas complementarias, motivos y ejemplos adecuados"),
(100,"fr_FR","Peut faire un exposé clair et bien structure sur un sujet complexe, développant et confirmant ses points de vue assez longuement à l'aide de points secondaires, de justifications et d'exemples pertinents"),
(101,"en_US","Can present a complex topic confidently and articulately to an audience unfamiliar with it, structuring and adapting the talk flexibly to meet the audience's needs"),
(101,"de_DE","Kann sicher und gut verständlich einem Publikum ein komplexes Thema vortragen, mit dem es nicht vertraut ist, und dabei die Rede flexibel den Bedürfnissen des Publikums anpassen und entsprechend strukturieren"),
(101,"es_ES","Presenta temas complejos con seguridad y de modo elocuente a un público que no conoce el tema, estructurando y adaptando su discurso con flexibilidad para satisfacer las necesidades del público"),
(101,"fr_FR","Peut présenter un sujet complexe, bien construit, avec assurance à un auditoire pour qui il n'est pas familier, en structurant et adaptant l'exposé avec souplesse pour répondre aux besoins de cet auditoire"),
(102,"en_US","CAN show visitors round and give a detailed description of a place"),
(102,"de_DE","KANN Besucher herumführen und eine detaillierte Beschreibung eines Ortes geben"),
(102,"es_ES","PUEDE \"guiar\" a los visitantes y dar una descripción detallada de un lugar"),
(102,"fr_FR","EST CAPABLE de faire visiter un lieu et en donner une description détaillée"),
(103,"en_US","CAN participate in casual conversations with appropriacy and good understanding of humour, irony and implicit cultural references"),
(103,"de_DE","KANN an Alltagsgesprächen angemessen und mit gutem Verständnis von Humor, Ironie und impliziten kulturellen Anspielungen teilnehmen"),
(103,"es_ES","PUEDE participar en conversaciones informales de forma apropiada y captar el humor, la ironía y las referencias culturales implícitas"),
(103,"fr_FR","EST CAPABLE de participer à des conversations à bâtons rompus de manière adéquate et de bien comprendre l'humour, l'ironie et les références culturelles implicites"),
(104,"en_US","CAN pick up nuances of meaning/opinion"),
(104,"de_DE","KANN Nuancen von Bedeutungen/Meinungen verstehen"),
(104,"es_ES","PUEDE comprender los matices de significado/opinión"),
(104,"fr_FR","EST CAPABLE de saisir les nuances de sens et d'opinion"),
(105,"en_US","CAN deal effectively with most routine transactions in a bank or post office"),
(105,"de_DE","KANN erfolgreich mit den meisten alltäglichen Transaktionen in der Bank oder im Postamt fertig werden"),
(105,"es_ES","PUEDE afrontar eficazmente la mayoría de las transacciones rutinarias en el banco o en correos"),
(105,"fr_FR","EST CAPABLE de faire face à la plupart des transactions habituelles à la poste ou à la banque"),
(106,"en_US","CAN ask very simple questions for information, such as 'What is this?'"),
(106,"de_DE","KANN sehr einfache Informationen erfragen, z..B. durch Fragen wie \"Was ist das?\""),
(106,"es_ES","PUEDE hacer preguntas muy sencillas para solicitar información, como por ejemplo \"¿qué es esto?\""),
(106,"fr_FR","EST CAPABLE de poser des questions simples du type \"Qu'est-ce que c'est ?\""),
(107,"en_US","CAN understand and ask simple questions and understand simple answers"),
(107,"de_DE","KANN einfache vorhersehbare Fragen verstehen und beantworten"),
(107,"es_ES","PUEDE comprender y responder preguntas previsibles sencillas"),
(107,"fr_FR","EST CAPABLE de comprendre des questions simples et courantes et d'y répondre"),
(108,"en_US","CAN express simple opinions using expressions such as 'I don't agree'"),
(108,"de_DE","KANN einfache Meinungen ausdrücken, in dem er/sie Ausdrücke verwendet wie \"Ich stimme dem nicht zu\""),
(108,"es_ES","PUEDE expresar opiniones sencillas utilizando expresiones tales como \"no estoy de acuerdo\".  "),
(108,"fr_FR","EST CAPABLE d'exprimer des opinions simples, en utilisant des expressions telles que \"Je ne suis pas d'accord\""),
(109,"en_US","Can exchange relevant information and give his/her opinion on practical problems when asked directly"),
(109,"de_DE","Kann relevante Informationen austauschen und, wenn direkt danach gefragt, die eigene Meinung zu einer praktischen Frage äußern"),
(109,"es_ES","Intercambia información pertinente y da su opinión sobre problemas prácticos cuando se le pregunta directamente"),
(109,"fr_FR","Peut échanger des informations pertinentes et donner son opinion sur des problèmes pratiques si on le/la sollicite directement"),
(110,"en_US","Can communicate in simple and routine tasks using simple phrases to ask for and provide things, to get simple information and to discuss what to do next"),
(110,"de_DE","Kann sich bei einfachen Routineaufgaben verständigen und dabei einfache Wendungen gebrauchen, um Dinge zu erbitten oder zu geben, einfache Informationen zu erfragen und zubesprechen, was man als Nächstes tun sollte"),
(110,"es_ES","Se comunica en charlas sencillas y cotidianas que requieren un intercambio de información sencillo y directo"),
(110,"fr_FR","Peut communiquer dans le cadre d'une tâche simple et routinière ne demandant qu'un échange d'information simple et direct"),
(111,"en_US","CAN give a short, simple presentation or demonstration on a familiar topic"),
(111,"de_DE","KANN eine kurze, einfache Präsentation oder Demonstration über ein vertrautes Thema geben"),
(111,"es_ES","PUEDE realizar una presentación o demostración corta y sencilla sobre un tema conocido"),
(111,"fr_FR","EST CAPABLE de faire une présentation courte et simple sur un thème familier"),
(112,"en_US","CAN take a limited part in a seminar or tutorial, provided that this is conducted sympathetically, using simple language"),
(112,"de_DE","KANN mit Einschränkungen an einem Seminar oder Kurs teilnehmen, vorausgesetzt, daß der Dozent auf ihn/sie eingeht und eine einfache Sprache benutzt"),
(112,"es_ES","PUEDE participar de forma limitada en un seminario o tutoría, siempre que exista un deseo de colaborar y se utilice un lenguaje sencillo"),
(112,"fr_FR","EST CAPABLE de participer de façon limitée à un séminaire ou à des travaux dirigés s'ils sont conduits avec bienveillance en utilisant un langage simple"),
(113,"en_US","Can take part in routine formal discussion of familiar subjects which is conducted in clearly articulated speech in the standard dialect and which involves the exchange of factual information, receiving instructions or the discussion of solutions to practical problems"),
(113,"de_DE","Kann an routinemäßigen formellen Diskussionen über vertraute Themen teilnehmen, bei denen es darum geht, Sachinformationen auszutauschen, Anweisungen entgegenzunehmen oder Lösungsmöglichkeiten für praktische Probleme zu diskutieren, sofern deutlich gesprochen und Standardsprache verwendet wird"),
(113,"es_ES","Es capaz de tomar parte en discusiones formales habituales sobre temas cotidianos cuando la lengua está articulada con claridad en nivel estándar, también puede tomar parte en discusiones que suponen un intercambio de información sobre hechos concretos o en las que se dan instrucciones o soluciones a problemas práctico"),
(113,"fr_FR","Peut prendre part à une discussion formelle courante sur un sujet familier conduite dans une langue standard clairement articulée et qui suppose l'échange d'informations factuelles, en recevant des instructions ou la discussion de solutions à des problèmes pratiques"),
(114,"en_US","CAN ask for clarification, but this needs to be given sympathetically in order for it to be understood"),
(114,"de_DE","KANN um Erläuterung bitten, aber die Erläuterung muß \"wohlwollend\" gegeben werden, damit sie verstanden werden kann"),
(114,"es_ES","PUEDE pedir aclaraciones, pero dicha aclaración deberá adaptarse a su capacidad de comprensión para que la entienda"),
(114,"fr_FR","EST CAPABLE de demander des éclaircissements mais ils devront être donnés avec bienveillance pour être compris"),
(115,"en_US","Can put over a point of view clearly, but has difficulty engaging in debate"),
(115,"de_DE","Kann einen Standpunkt klar machen, hat aber Schwierigkeiten wenn er/sie sich auf eine Debatte einlässt"),
(115,"es_ES","Puede plantear un punto de vista con claridad, pero le resulta difícil participar en el debate"),
(115,"fr_FR","Peut exprimer clairement un point de vue mais a du mal à engager un débat"),
(116,"en_US","Can explain why something is a problem, discuss what to do next, compare and contrast alternatives"),
(116,"de_DE","Kann erklären, warum etwas ein Problem ist, kann diskutieren, was man als Nächstes tun sollte, und kann Alternativen vergleichen und einander gegenüberstellen"),
(116,"es_ES","Explica los motivos de un problema, discute sobre los pasos que se deben seguir, compara y contrasta alternativas"),
(116,"fr_FR","Peut expliquer pourquoi quelque chose pose problème, discuter de la suite à donner, comparer et opposer les solutions"),
(117,"en_US","Can give brief comments on the views of others"),
(117,"de_DE","Kann die Standpunkte anderer kurz kommentieren"),
(117,"es_ES","Realiza breves comentarios sobre los puntos de vista de otras persona"),
(117,"fr_FR","Peut commenter brièvement le point de vue d'autrui"),
(118,"en_US","Can summarise and give his or her opinion about a short story, article, talk, discussion, interview, or documentary and answer further questions of detail"),
(118,"de_DE","Kann eine kurze Geschichte, einen Artikel, einen Vortrag, ein Interview oder eine Dokumentarsendung zusammenfassen, dazu Stellung nehmen und Informationsfragen dazu beantworten"),
(118,"es_ES","Resume y da su opinión sobre relatos, artículos, charlas, discusiones, entrevistas o documentales breves, y responde a preguntas complementarias que requieren detalles"),
(118,"fr_FR","Peut résumer – en donnant son opinion – un bref récit, un article, un exposé, une discussion, une interview ou un documentaire et répondre à d'éventuelles questions complémentaires de détail"),
(119,"en_US","CAN give a clear presentation on a familiar topic"),
(119,"de_DE","KANN eine klare Präsentation über ein vertrautes Thema geben"),
(119,"es_ES","PUEDE realizar una presentación clara sobre un tema conocido"),
(119,"fr_FR","EST CAPABLE de présenter clairement un thème familier"),
(120,"en_US","CAN answer predictable or factual questions"),
(120,"de_DE","KANN vorhersehbare und faktische Fragen beantworten"),
(120,"es_ES","PUEDE responder a preguntas previsibles o de carácter objetivo"),
(120,"fr_FR","EST CAPABLE de répondre à des questions courantes et factuelles"),
(121,"en_US","CAN check that all instructions are understood"),
(121,"de_DE","KANN überprüfen, daß er/sie die Anweisungen richtig verstanden hat"),
(121,"es_ES","PUEDE comprobar que ha entendido todas las indicaciones"),
(121,"fr_FR","EST CAPABLE de vérifier que toutes les indications sont comprises"),
(122,"en_US","Can express his/her ideas and opinions with precision, present and respond to complex lines of argument convincingly"),
(122,"de_DE","Kann seine/ihre Gedanken und Meinungen präzise ausdrücken, überzeugend argumentieren und auf komplexe Argumentationen anderer reagieren"),
(122,"es_ES","Expresa sus ideas y opiniones con precisión, presenta líneas argumentales complejas y responde a ellas con convicción"),
(122,"fr_FR","Peut exprimer ses idées et ses opinions avec précision et argumenter avec conviction sur des sujets complexes et réagir de même aux arguments d'autrui"),
(123,"en_US","Can outline an issue or a problem clearly, speculating about causes or consequences, and weighing advantages and disadvantages of different approaches"),
(123,"de_DE","Kann eine Angelegenheit oder ein Problem klar darlegen, dabei Vermutungen über Ursachen und Folgen anstellen und die Vor- und Nachteile verschiedener Ansätze gegeneinander abwägen"),
(123,"es_ES","Esboza un asunto o un problema con claridad, especulando sobre las causas o consecuencias y comparando las ventajas y desventajas de diferentes enfoques"),
(123,"fr_FR","Peut esquisser clairement à grands traits une question ou un problème, faire des spéculations sur les causes et les conséquences, et mesurer les avantages et les inconvénients des différentes approches"),
(124,"en_US","Can synthesise and report information and arguments from a number of sources"),
(124,"de_DE","Kann Informationen und Argumente aus verschiedenen Quellen zusammenfassen und wiedergeben"),
(124,"es_ES","Sintetiza y comunica información y argumentos procedentes de varias fuentes"),
(124,"fr_FR","Peut faire la synthèse d'informations et d'arguments issus de sources différentes et en rendre compte"),
(125,"en_US","CAN ask questions, for example for reasons, clarification etc."),
(125,"de_DE","KANN Fragen stellen, z. B. nach Ursachen, Erläuterungen etc."),
(125,"es_ES","PUEDE hacer preguntas, por ejemplo para pedir razones, aclaraciones, etc."),
(125,"fr_FR","EST CAPABLE de poser des questions concernant, par exemple, des motifs de demander, des éclaircissements, etc."),
(126,"en_US","CAN rebut criticisms without causing offence"),
(126,"de_DE","KANN Kritik zurückweisen, ohne beleidigend zu wirken"),
(126,"es_ES","PUEDE rebatir las críticas sin ofender"),
(126,"fr_FR","EST CAPABLE de faire face aux critiques sans agressivité"),
(127,"en_US","CAN give coherent explanations of a theoretical nature"),
(127,"de_DE","KANN zusammenhängende Erläuterungen theoretischer Art geben"),
(127,"es_ES","PUEDE dar explicaciones coherentes de carácter teórico"),
(127,"fr_FR","EST CAPABLE de donner des explications théoriques cohérentes"),
(128,"en_US","CAN give an effective presentation or demonstration"),
(128,"de_DE","KANN eine erfolgreiche Präsentation oder Demonstration geben"),
(128,"es_ES","PUEDE realizar una presentación o demonstración efectiva"),
(128,"fr_FR","EST CAPABLE de faire efficacement une présentation ou une démonstration"),
(129,"en_US","CAN answer unpredictable questions of a factual nature"),
(129,"de_DE","KANN unvorhersehbare Fragen faktischer Art beantworten"),
(129,"es_ES","PUEDE responder a preguntas imprevisibles de carácter objetivo"),
(129,"fr_FR","EST CAPABLE de répondre à des questions imprévues qui portent sur des faits"),
(130,"en_US","CAN make all necessary arrangements regarding practical arrangements for study in or out of classroom with teachers, lecturers, lab and library staff, etc."),
(130,"de_DE","KANN alle Vereinbarungen treffen, die für die praktische Durchführung des Studiums innerhalb und außerhalb des Klassenzimmers notwendig sind, d. h. mit Lehrern, Dozenten, Labor- und Bibliothekspersonal etc."),
(130,"es_ES","PUEDE ponerse de acuerdo con profesores, personal de biblioteca, laboratorio, etc para cualquier cuestión relacionada con el estudio dentro y fuera del aula"),
(130,"fr_FR","EST CAPABLE de prendre toutes les dispositions nécessaires pour l'organisation pratique du travail en classe ou hors de la classe avec les enseignants et le personnel du laboratoire et de la bibliothèque"),
(131,"en_US","CAN reformulate questions if misunderstood"),
(131,"de_DE","KANN Fragen, wenn sie mißverstanden wurden, umformulieren"),
(131,"es_ES","PUEDE reformular sus preguntas si no le comprenden"),
(131,"fr_FR","EST CAPABLE de reformuler des questions si elles sont mal comprises"),
(132,"en_US","CAN make critical remarks / express disagreement without causing offence"),
(132,"de_DE","KANN Kritik äußern/einen anderen Standpunkt einnehmen, ohne beleidigend zu wirken"),
(132,"es_ES","PUEDE hacer comentarios críticos/expresar su desacuerdo sin ofender"),
(132,"fr_FR","EST CAPABLE de faire des remarques critiques, d'exprimer son désaccord sans offenser les autres"),
(133,"en_US","CAN take an active part in most kinds of seminars or tutorials"),
(133,"de_DE","KANN aktiv an den meisten Seminaren oder Kursen teilnehmen"),
(133,"es_ES","PUEDE participar de forma active en la mayoría de los diferentes seminarios o tutorías.  "),
(133,"fr_FR","EST CAPABLE de participer à la plupart des séminaires ou travaux dirigés"),
(134,"en_US","CAN get and hold on to his/her turn to speak"),
(134,"de_DE","KANN seinen Sprechanteil am Gespräch behaupten"),
(134,"es_ES","PUEDE tomar la palabra y mantenerla"),
(134,"fr_FR","EST CAPABLE de prendre son tour de parole et de le garder"),
(135,"en_US","CAN rebut counter-arguments"),
(135,"de_DE","KANN Gegenargumente zurückweisen"),
(135,"es_ES","PUEDE rebatir argumentos contrarios.  "),
(135,"fr_FR","EST CAPABLE de réfuter des contre-arguments"),
(136,"en_US","Can reply in an interview to simple direct questions spoken very slowly and clearly in direct non-idiomatic speech about personal details"),
(136,"de_DE","Kann in einem Interviewgespräch einfache, direkte Fragen zur Person beantworten, wenn die Fragen langsam, deutlich und in direkter, nicht-idiomatischer Sprache gestellt werden"),
(136,"es_ES","Responde en una entrevista a preguntas sencillas y directas sobre datos personales, si se habla muy despacio y con claridad sin modismos ni frases hechas"),
(136,"fr_FR","Peut répondre dans un entretien à des questions personnelles posées très lentement et clairement dans une langue directe et non idiomatique"),
(137,"en_US","CAN offer some help to a client/customer, for example, 'I'll give you our new catalogue'"),
(137,"de_DE","KANN dem Kunden einfache Hilfe anbieten, z. B. \"Ich gebe Ihnen unseren neuen Katalog\""),
(137,"es_ES","PUEDE ofrecer ayuda a un cliente, por ejemplo, \"Este es nuestro nuevo catálogo\""),
(137,"fr_FR","EST CAPABLE de proposer de l'aide à un client, par exemple \"Je vais vous donner notre nouveau catalogue\""),
(138,"en_US","CAN state simple requirements within own job area, for example 'I want to order 25 of...'"),
(138,"de_DE","KANN innerhalb seines/ihres eigenen Arbeitsgebiets einfache Bedürfnisse äußern, z. B. \"Ich möchte 25... bestellen.\"  "),
(138,"es_ES","PUEDE expresar peticiones muy sencillas dentro de su propio ámbito de trabajo, por ejemplo \"Quiero pedir 25…\""),
(138,"fr_FR","EST CAPABLE de formuler des demandes simples concernant son travail, comme \"Je voudrais commander 25 unités de...\""),
(139,"en_US","CAN exchange opinions on familiar, predictable matters, for example, involving straightforward discussions of the 'This is better because...' type"),
(139,"de_DE","KANN sich äußern zu alltäglichen, vorhersehbaren Vorgängen, z.B. wenn diese nur eine einfache Diskussion verlangen wie \"Das wäre besser, weil...\""),
(139,"es_ES","PUEDE intercambiar opiniones sobre temas conocidos, previsibles, por ejemplo, mediante argumentaciones sencillas del tipo \"Esto es mejor porque…\""),
(139,"fr_FR","EST CAPABLE d'échanger des points de vue sur des sujets courants du moment que les discussions ne dépassent pas le cadre de \"Ceci est mieux parce que...\""),
(140,"en_US","Can discuss what to do next, making and responding to suggestions, asking for and giving directions"),
(140,"de_DE","Kann diskutieren, was man als Nächstes tun sollte, kann Vorschläge machen und auf Vorschläge reagieren, kann um Anleitungen bitten und Anleitungen geben"),
(140,"es_ES","Discute los pasos que hay que seguir, planteando sugerencias y respondiendo a las sugerencias de los demás, pidiendo y dando indicaciones"),
(140,"fr_FR","Peut discuter de ce que l'on fera ensuite, répondre à des suggestions et en faire, demander des directives et en donner"),
(141,"en_US","Can communicate in simple and routine tasks using simple phrases to ask for and provide things, to get simple information and to discuss what to do next"),
(141,"de_DE","Kann sich bei einfachen Routineaufgaben verständigen und dabei einfache Wendungen gebrauchen, um Dinge zu erbitten oder zu geben, einfache Informationen zu erfragen und zu besprechen, was man als Nächstes tun sollte"),
(141,"es_ES","Es capaz de comunicarse en tareas cotidianas utilizando frases sencillas para pedir y ofrecer cosas, para conseguir información sencilla y para discutir los pasos que hay que seguir"),
(141,"fr_FR","Peut communiquer au cours de simples tâches courantes en utilisant des expressions simples pour avoir des objets et en donner, pour obtenir une information simple et discuter de la suite à donner"),
(142,"en_US","Can answer simple questions and respond to simple statements in an interview"),
(142,"de_DE","Kann in einem Interview einfache Fragen beantworten und auf einfache Feststellungen reagieren"),
(142,"es_ES","Responde a preguntas y afirmaciones sencillas durante una entrevista"),
(142,"fr_FR","Peut répondre à des questions simples et réagir à des déclarations simples dans un entretien"),
(143,"en_US","Can make him/herself understood in an interview and communicate ideas and information on familiar topics, provided he/she can ask for clarification occasionally, and is given some help to express what he/she wants to"),
(143,"de_DE","Kann sich in einem Interview verständlich machen und Informationen und Ideen zu vertrauten Themen mitteilen, vorausgesetzt, er/sie kann gelegentlich um Klärung bitten und erhält Hilfe, das auszudrücken, was er/sie sagen möchte"),
(143,"es_ES","Se hace comprender en una entrevista y cuando comunica ideas e información sobre temas cotidianos, siempre que pueda pedir de vez en cuando que le aclaren lo dicho y que le ayuden a expresar lo que quiere decir"),
(143,"fr_FR","Peut se faire comprendre dans un entretien et communiquer des idées et de l'information sur des sujets familiers à condition de pouvoir faire clarifier à l'occasion et d'être aidé pour exprimer ce qu'il/elle veut"),
(144,"en_US","CAN make an outgoing call and pass on simple, prepared messages, for example 'Mr X's flight is late; he will arrive this afternoon'"),
(144,"de_DE","KANN ein Telefongespräch führen und einfache, vorbereitete Nachrichten weitergeben, z. B. \"Der Flug von Herrn X hat Verspätung; er kommt heute nachmittag an.\""),
(144,"es_ES","PUEDE realizar una llamada y transmitir mensajes preparados muy sencillos, por ejemplo, \"El vuelo del señor X viene con retraso; él llagará esta tarde\""),
(144,"fr_FR","EST CAPABLE de faire un appel et de laisser de simples messages déjà préparés, comme par exemple, 'Le vol de Mr. X est en retard ; il arrivera cet après-midi\""),
(145,"en_US","CAN state routine requirements within own area of work (e.g. asking for typing to be done)"),
(145,"de_DE","KANN alltägliche Bedürfnisse innerhalb des eigenen Arbeitsbereichs benennen (z. B. um die Erledigung von Schreibarbeit bitten)"),
(145,"es_ES","PUEDE expresar peticiones rutinarias dentro de su propio ámbito de trabajo (por ejemplo, pedir que le pasen algo a máquina)"),
(145,"fr_FR","EST CAPABLE de formuler des demandes courantes dans le domaine de son travail (demander qu'un papier soit dactylographié)"),
(146,"en_US","CAN greet a visitor and engage in a limited conversation for a short period of time, for example enquiring about a visitor's journey, hotel etc."),
(146,"de_DE","KANN einen Besucher begrüßen und für eine begrenzte Zeit sich mit ihm unterhalten, z. B. sich erkundigen über die Reise eines Besuchers, sein Hotel etc."),
(146,"es_ES","PUEDE saludar a las visitas y entablar una conversación limitada durante un corto periodo de tiempo, por ej. Interesarse por su viaje, el hotel etc."),
(146,"fr_FR","EST CAPABLE d'accueillir un visiteur et engager une conversation avec lui durant une courte période de temps, par exemple, discuter de son voyage, de l'hôtel, etc."),
(147,"en_US","CAN offer advice to clients within own job area on simple matters (e.g. 'This model will give you better copies, but it is more expensive')"),
(147,"de_DE","KANN den Kunden innerhalb des eigenen Arbeitsgebiets in einfachen Angelegenheiten beraten (z.B. Dieses Modell macht bessere Kopien, ist aber teurer)"),
(147,"es_ES","PUEDE ofrecer consejo a clientes sobre cuestiones sencillas dentro de su propio ámbito de trabajo (por ej.\"Este modelo le proporcionará mejores copias, pero es más caro\")"),
(147,"fr_FR","EST CAPABLE de donner son avis aux clients dans le domaine de son travail sur des points simples (\"Avec ce modèle vous aurez de meilleures copies, mais il est plus cher\")"),
(148,"en_US","Can exchange, check and confirm accumulated factual information on familiar routine and non-routine matters within his/her field with some confidence"),
(148,"de_DE","Kann im eigenen Sachgebiet mit einer gewissen Sicherheit größere Mengen von Sachinformationen über vertraute Routineangelegenheiten und über weniger routinemäßige Dinge austauschen"),
(148,"es_ES","Intercambia, comprueba y confirma con cierta confianza información concreta sobre asuntos, cotidianos o no, dentro de su especialidad"),
(148,"fr_FR","Peut échanger avec une certaine assurance un grand nombre d'informations factuelles sur des sujets courants ou non, familiers à son domaine"),
(149,"en_US","Can describe how to do something, giving detailed instructions"),
(149,"de_DE","Kann beschreiben, wie man etwas macht, und kann genaue Anweisungen geben "),
(149,"es_ES","Describe la forma de realizar algo dando instrucciones detalladas"),
(149,"fr_FR","Peut expliquer comment faire quelque chose en donnant des instructions détaillées"),
(150,"en_US","Can explain why something is a problem, discuss what to do next, compare and contrast alternatives"),
(150,"de_DE","Kann erklären, warum etwas ein Problem ist, kann diskutieren, was man als Nächstes tun sollte, und kann Alternativen vergleichen und einander gegenüberstellen"),
(150,"es_ES","Explica los motivos de un problema, discute sobre los pasos que se deben seguir, compara y contrasta alternativas"),
(150,"fr_FR","Peut expliquer pourquoi quelque chose pose problème, discuter de la suite à donner, comparer et opposer les solutions"),
(151,"en_US","Can give brief comments on the views of others"),
(151,"de_DE","Kann die Standpunkte anderer kurz kommentieren"),
(151,"es_ES","Realiza breves comentarios sobre los puntos de vista de otras personas"),
(151,"fr_FR","Peut commenter brièvement le point de vue d'autrui"),
(152,"en_US","Can provide concrete information required in an interview but does so with limited precision"),
(152,"de_DE","Kann in einem Interview- oder Konsultationsgespräch konkrete Auskünfte geben (z.B. beim Arzt Symptome beschreiben), tut das aber mit begrenzter Genauigkeit"),
(152,"es_ES","Proporciona la información concreta que se requiere en una entrevista o en una consulta (por ejemplo, describe síntomas a un médico), pero lo hace con una precisión limitada"),
(152,"fr_FR","Peut fournir des renseignements concrets exigés dans un entretien ou une consultation (par exemple, décrire des symptômes à un médecin) mais le fait avec une précision limitée"),
(153,"en_US","CAN put her/his point across persuasively when talking, for example about a familiar product"),
(153,"de_DE","KANN in einem Gespräch seine Meinung überzeugend darstellen, z. B. über ein bekanntes Produkt"),
(153,"es_ES","PUEDE expresar su punto de vista de manera convincente al hablar, por ejemplo, de un producto conocido"),
(153,"fr_FR","EST CAPABLE d'exposer son opinion et d'être convaincant quand il parle, par exemple, d'un produit familier"),
(154,"en_US","Can give a clear, detailed description of how to carry out a procedure"),
(154,"de_DE","Kann klar, detailliert beschreiben, wie bei einem Verfahren vorgegangen werden kann"),
(154,"es_ES","Realiza descripciones claras y detalladas acerca de la forma de llevar a cabo un procedimiento "),
(154,"fr_FR","Peut faire la description claire et détaillée d'une démarche"),
(155,"en_US","Can understand and exchange complex information and advice on the full range of matters related to his/her occupational role"),
(155,"de_DE","Kann komplexe Informationen und Ratschläge in Zusammenhang mit allen Dingen, die mit seinem/ihrem Beruf zu tun haben, verstehen und austauschen"),
(155,"es_ES","Comprende e intercambia información compleja y consejos sobre todos los asuntos relacionados con su profesión"),
(155,"fr_FR","Peut comprendre et échanger une information complexe et des avis sur une gamme étendue de sujets relatifs à son rôle professionnel"),
(156,"en_US","Can outline an issue or a problem clearly, speculating about causes or consequences, and weighing advantages and disadvantages of different approaches"),
(156,"de_DE","Kann eine Angelegenheit oder ein Problem klar darlegen, dabei Vermutungen über Ursachen und Folgen anstellen und die Vor- und Nachteile verschiedener Ansätze gegeneinander abwägen"),
(156,"es_ES","Esboza un asunto o un problema con claridad, especulando sobre las causas o consecuencias y comparando las ventajas y desventajas de diferentes enfoque"),
(156,"fr_FR","Peut esquisser clairement à grands traits une question ou un problème, faire des spéculations sur les causes et les conséquences, et mesurer les avantages et les inconvénients des différentes approches"),
(157,"en_US","Can carry out an effective, fluent interview, departing spontaneously from prepared questions, following up and probing interesting replies"),
(157,"de_DE","Kann wirksam und flüssig ein Interviewgespräch führen, von vorbereiteten Fragen spontan abweichen, auf interessante Antworten näher eingehen und nachfragen"),
(157,"es_ES","Realiza entrevistas eficaces y fluidas, incluso alejándose espontáneamente de las preguntas preparadas, siguiendo el hilo y dando repuestas interesantes"),
(157,"fr_FR","Peut conduire un entretien avec efficacité et aisance, en s'écartant spontanément des questions préparées et en exploitant et relançant les réponses intéressantes"),
(158,"en_US","Can express his/her ideas and opinions with precision, present and respond to complex lines of argument convincingly"),
(158,"de_DE","Kann seine/ihre Gedanken und Meinungen präzise ausdrücken, überzeugend argumentieren und auf komplexe Argumentationen anderer reagieren"),
(158,"es_ES","Expresa sus ideas y opiniones con precisión, presenta líneas argumentales complejas y responde a ellas con convicción"),
(158,"fr_FR","Peut exposer ses idées et ses opinions et argumenter avec conviction sur des sujets complexes et réagir de même aux arguments d'autrui"),
(159,"en_US","Can contribute, account for and sustain his/her opinion, evaluate alternative proposals and make and respond to hypotheses"),
(159,"de_DE","Kann zur Diskussion beitragen, den eigenen Standpunkt begründen und verteidigen, alternative Vorschläge beurteilen, Hypothesen aufstellen und auf Hypothesen anderer reagieren"),
(159,"es_ES","Ofrece, explica y defiende sus opiniones, evalúa las propuestas alternativas, formula hipótesis y responde a éstas"),
(159,"fr_FR","Peut exprimer, justifier et défendre son opinion, évaluer d'autres propositions ainsi que répondre à des hypothèses et en faire"),
(160,"en_US","CAN take or leave routine messages, ask for clarification or elaboration where these are not expressed clearly, with only occasional misunderstanding of facts"),
(160,"de_DE","KANN Routinenachrichten aufnehmen oder hinterlassen, um Klärung oder Erläuterung bitten, falls diese undeutlich waren, wobei nur gelegentlich Mißverständnisse auftreten"),
(160,"es_ES","PUEDE recoger o dar mensajes rutinarios y pedir aclaraciones o explicaciones detalladas si los mensajes no están claramente expresados, con sólo algún malentendido ocasional de los datos"),
(160,"fr_FR","EST CAPABLE de prendre ou de laisser des messages courants, de demander des éclaircissements si ceux-ci ne sont pas exprimés clairement, faisant seulement quelques erreurs occasionnelles de compréhension"),
(161,"en_US","CAN give detailed information and state detailed requirements within familiar area of work"),
(161,"de_DE","KANN genaue Informationen geben und Bedürfnisse äußern in einem ihm/ihr vertrauten Arbeitsbereich"),
(161,"es_ES","PUEDE aportar información detallada y establecer condiciones detalladas dentro de un campo conocido"),
(161,"fr_FR","EST CAPABLE de donner des informations détaillées et formuler des demandes détaillées dans le domaine familier du travail"),
(162,"en_US","CAN argue his/her case effectively, justifying, if necessary, a need for service and specifying needs precisely"),
(162,"de_DE","KANN erfolgreich seine Meinung vertreten und, falls erforderlich, die Notwendigkeit von Leistungen begründen und Bedürfnisse genau erklären"),
(162,"es_ES","PUEDE exponer su caso de manera eficaz, justificando, si es preciso, la necesidad de un servicio y especificando las necesidades con precisión"),
(162,"fr_FR","EST CAPABLE d'argumenter sur un cas d'espèce, justifier, si nécessaire, le besoin d'un service et préciser des besoins clairement"),
(163,"en_US","CAN answer questions outside own immediate area of work"),
(163,"de_DE","KANN Fragen, die nicht zu seinem/ihrem unmittelbaren Arbeitsgebiet gehören, beantworten.  "),
(163,"es_ES","PUEDE contestar preguntas ajenas a su propio ámbito de trabajo.  "),
(163,"fr_FR","EST CAPABLE de répondre à des questions sans rapport avec son domaine de travail"),
(164,"en_US","CAN engage in an extended conversation with a visitor on matters within her/his authority/competence"),
(164,"de_DE","KANN ein längeres Gespräch mit einem Gast über Angelegenheiten seiner/ihrer Kompetenz führen"),
(164,"es_ES","PUEDE participar en una conversación extensa con una visita sobre temas propios de su competencia"),
(164,"fr_FR","EST CAPABLE de participer à une discussion assez longue avec un visiteur sur des sujets de sa compétence"),
(165,"en_US","CAN give detailed information and deal with most routine problems that are likely to arise"),
(165,"de_DE","KANN detaillierte Informationen geben und die meisten alltäglichen Probleme bewältigen, die anfallen könnten"),
(165,"es_ES","PUEDE aportar información detallada y resolver los problemas más rutinarios que puedan surgir"),
(165,"fr_FR","EST CAPABLE de donner des informations détaillées et de faire face à la plupart des problèmes courants"),
(166,"en_US","CAN ask questions outside own immediate area of work (e.g. asking for external legal or financial advice)"),
(166,"de_DE","KANN Fragen außerhalb des eigenen direkten Arbeitsbereichs stellen (z. B. einen juristischen oder finanziellen Rat von außerhalb einholen)"),
(166,"es_ES","PUEDE formular preguntas ajenas a su propio ámbito de trabajo (por ej. pedir consejo legal o financiero externo)"),
(166,"fr_FR","EST CAPABLE de poser des questions sans rapport avec son domaine de travail (demander un avis financier ou juridique extérieur)"),
(167,"en_US","CAN advise on/handle complex, delicate or contentious issues, e.g. legal or financial situations"),
(167,"de_DE","KANN in komplizierten, heiklen und umstrittenen Angelegenheiten beraten, z.B. bei juristischen und finanzpolitischen Fragen"),
(167,"es_ES","PUEDE tratar o aconsejar sobre cuestiones complejas, delicadas o polémicas, por ej. Situaciones legales o financieras"),
(167,"fr_FR","EST CAPABLE de conseiller/faire face aux problèmes délicats et conflictuels complexes, par exemple les situations juridiques et financières"),
(168,"en_US","Can participate fully in an interview, as either interviewer or interviewee, expanding and developing the point being discussed fluently without any support, and handling interjections well"),
(168,"de_DE","Kann uneingeschränkt an einem Interview teilnehmen, sowohl als Interviewer/in als auch als Interviewte/r; kann die diskutierte Frage flüssig und ohne fremde Hilfe ausführen und entwickeln; kann gut mit Einwürfen umgehen"),
(168,"es_ES","Participa totalmente en una entrevista como entrevistador o como entrevistado, ampliando y desarrollando las ideas discutidas con fluidez y sin apoyo y haciendo un buen uso de las interjeccion"),
(168,"fr_FR","Peut conduire un entretien avec efficacité et aisance, en s'écartant spontanément des questions préparées et en exploitant et relançant les réponses intéressantes"),
(169,"en_US","CAN deal with unpredictable questions"),
(169,"de_DE","KANN mit unvorhersehbaren Fragen umgehen"),
(169,"es_ES","PUEDE hacer frente a preguntas imprevisibles"),
(169,"fr_FR","EST CAPABLE de traiter de questions non prévues"),
(170,"en_US","CAN contribute effectively to meetings and seminars within own area of work"),
(170,"de_DE","KANN erfolgreich zu Besprechungen und Seminaren innerhalb des eigenen Arbeitsgebiets beitragen"),
(170,"es_ES","PUEDE contribuir de manera eficaz a reuniones y seminarios dentro de su propio ámbito de trabajo"),
(170,"fr_FR","EST CAPABLE de contribuer efficacement à des réunions et des séminaires dans le domaine de son travail"),
(171,"en_US","CAN argue effectively for or against a case, and has sufficient language to be able to talk about/discuss most aspects of her/his work"),
(171,"de_DE","KANN erfolgreich gegen oder für einen Standpunkt diskutieren und ist sprachlich in der Lage, die meisten Aspekte seiner/ihrer Arbeit zu besprechen"),
(171,"es_ES","PUEDE discutir de manera eficaz a favor o en contra de un caso, y posee el suficiente dominio del lenguaje para poder hablar/discutir sobre la mayoría de los aspectos relacionados con su trabajo"),
(171,"fr_FR","EST CAPABLE d'argumenter pour ou contre un cas et a assez de ressources langagières pour parler ou discuter de la plupart des aspects de son travail"),
(172,"en_US","CAN use the telephone confidently, even if the line is bad or the caller has a non-standard accent"),
(172,"de_DE","KANN sicher das Telephon benutzen, auch wenn die Verbindung schlecht ist oder der Anrufer einen ungewöhnlichen Akzent hat"),
(172,"es_ES","PUEDE utilizar el teléfono con seguridad, incluso si la línea es mala o la persona que llama no tiene un acento estándar"),
(172,"fr_FR","EST CAPABLE d'utiliser le téléphone en toute confiance, même si la ligne est mauvaise ou l'interlocuteur a un accent qui ne correspond pas aux normes standard");
